user:
  login_success: 21001
  login_fail: 51001
  register_success: 22001
  register_fail: 52001
  validity_username_success: 22002
  validity_username_fail: 52002
  select_all: 23001
  select_all_fail: 53001