server:
  port: 8080
  display-name: OWN
  context-path: /own
  jsp-servlet:
    init-parameters:
      development: true
  session:
    timeout: 1800

info:
  version: "1.0.0"

spring:
  profiles:
    include: redis, mongodb
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  jackson:
    time-zone: GMT+8
logging:
  config=classpath:log4j2.xml