server:
  port: 8080
  display-name: OWN
  context-path: /own
  jsp-servlet:
    init-parameters:
      development: true
  session:
    timeout: 1800

info:
  version: "1.0.0"

spring:
  thymeleaf:
    mode: LEGACYHTML5
#  resources:
#    static-locations: classpath:/static/
#  mvc:
#    static-path-pattern: /static/**
  profiles:
    include: redis, mongodb
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  jackson:
    time-zone: GMT+8
#logging:
#  config: classpath:log4j2.xml
#  path: logs
#  file: test.log
#  level: info
#  pattern:
#    console: "%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n"
#    file: "%d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n"