server:
  port: 8080
  display-name: OWN
  context-path: /
  jsp-servlet:
    init-parameters:
      development: true
  session:
    timeout: 1800

info:
  version: "1.0.0"
mybatis:
  mapperLocations: classpath:mapper/**/*Mapper.xml


spring:
  messages:

    basename: security/il8n/messages_zh_CN
    encoding: utf-8
  resources:
    static-locations: classpath:/
#  mvc:
#    static-path-pattern: /static/**
  profiles:
    include: druid, redis, rescode
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  jackson:
    time-zone: GMT+8
security:
  basic:
    enabled: false


#mybatis日志输出
logging:
  level:
    com.cy.own.dao: debug
    org:
      mybatis: debug
