user:
  default_pwd: admin_123
  code:
    login_success: 21001
    login_fail: 51001
    register_success: 22001
    register_fail: 52001
    validity_username_success: 22002
    validity_username_fail: 52002
    select_user_all: 23001
    select_user_all_fail: 53001
    update_user: 23002
    update_user_fail: 53002
    insert_user: 23003
    insert_user_fail: 53003
  msg:
    login_success: 登录成功
    login_fail: 登录失败
    register_success: 注册成功
    register_fail: 注册失败
    validity_username_success: 用户名可用！
    validity_username_fail: 用户名已存在！
    select_user_all: 查询所有用户成功！
    select_user_all_fail: 查询所有用户失败！
    update_user: 编辑用户信息成功！
    update_user_fail: 编辑用户信息失败，请刷新重试！
    insert_user: 添加用户成功！
    insert_user_fail: 添加用户失败，请刷新重试！